spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: javatechie4u@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
